[package]
name = "MiraMigrator"
version = "1.0.0"
edition = "2024"
authors = ["Lumira <2301385546@qq.com>"]

[dependencies]
regex = "1.8.5"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
sanitize-filename = "0.6.0"
serde_json = "1.0.140"
toml = "0.8.22"
zip = "3.0.0"
